modLoader="javafml"
loaderVersion="[37,)"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId="bubatzcraftforge"
version="0.1.0"
displayName="Bubatzcraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/dienudel32/bubatzcraft"
logoFile="logo.png"
authors="Die Nudel, Villtex, kichelstein"
description='''
Minecraft Drug Mod
'''

[[dependencies.bubatzcraftforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




